// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicId } from './ComicId'
import type { ItemId } from './ItemId'
import type { StorylineFactSegment } from './StorylineFactSegment'

export type ActiveStorylineSummary = {
    id: ItemId
    startComicId: ComicId
    endComicId: ComicId | null
    /**
     * RLE of attachment from `startComicId` to `endComicId ?? latest known
     * comic`. Bounded by toggle count, not comic count.
     */
    segments: Array<StorylineFactSegment>
}
