// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicId } from './ComicId'

export type AddAdvanceComicBody = {
    comicId: ComicId
    title: string
    tagline?: string
    publishDate?: string
    isAccuratePublishDate?: boolean
    isGuestComic?: boolean
    isNonCanon?: boolean
}
