// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicId } from './ComicId'
import type { ExistingItem } from './ExistingItem'
import type { NewItem } from './NewItem'
import type { Token } from './Token'

export type AddItemToComicBody = { token: Token; comicId: ComicId } & (
    | NewItem
    | ExistingItem
)
