// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Exclusion } from './Exclusion'

export type AllQuery = { exclude?: Exclusion }
