// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BestFriendPair } from './BestFriendPair'
import type { CoAppearanceCharacterMeta } from './CoAppearanceCharacterMeta'

export type BestFriendResponse = {
    characters: { [key in number]: CoAppearanceCharacterMeta }
    pairs: Array<BestFriendPair>
}
