// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Exclusion } from './Exclusion'
import type { Inclusion } from './Inclusion'
import type { Sorting } from './Sorting'

export type ByIdQuery = {
    exclude?: Exclusion
    include?: Inclusion
    sorting?: Sorting
}
