// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CastTurnoverYear = {
    year: number
    newChars: number
    continuingChars: number
    returningChars: number
    droppedChars: number
}
