// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoAppearanceCharacterMeta } from './CoAppearanceCharacterMeta'
import type { CoAppearancePair } from './CoAppearancePair'

export type CoAppearancesResponse = {
    characters: { [key in number]: CoAppearanceCharacterMeta }
    pairs: Array<CoAppearancePair>
}
