// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemId } from './ItemId'

export type CoAppearancePair = {
    character1Id: ItemId
    character2Id: ItemId
    comicsTogether: number
}
