// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicId } from './ComicId'
import type { EditorData } from './EditorData'
import type { ItemNavigationData } from './ItemNavigationData'
import type { MissingComic } from './MissingComic'
import type { PresentComic } from './PresentComic'

export type Comic = {
    comic: ComicId
    editorData: EditorData
    allItems?: Array<ItemNavigationData>
} & (MissingComic | PresentComic)
