// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AvgCastPerYear } from './AvgCastPerYear'
import type { MostCrowdedComic } from './MostCrowdedComic'

export type CrowdedComicsResponse = {
    topComics: Array<MostCrowdedComic>
    avgPerYear: Array<AvgCastPerYear>
}
