// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebutCharacter } from './DebutCharacter'

export type DebutYear = { year: number; characters: Array<DebutCharacter> }
