// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MissingEditorData } from './MissingEditorData'
import type { PresentEditorData } from './PresentEditorData'

export type EditorData = MissingEditorData | PresentEditorData
