// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicId } from './ComicId'
import type { ItemId } from './ItemId'
import type { ItemType } from './ItemType'

export type ItemList = {
    id: ItemId
    shortName: string
    name: string
    type: ItemType
    color: string
    count: number
    /**
     * Only meaningful for `type === 'storyline'`; `null` for cast/location.
     */
    startComicId: ComicId | null
    /**
     * Only meaningful for `type === 'storyline'`; `null` means either
     * ongoing or not a storyline.
     */
    endComicId: ComicId | null
}
