// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterMeta } from './CharacterMeta'
import type { LocationSpotlightYear } from './LocationSpotlightYear'

export type LocationSpotlightResponse = {
    locations: { [key in number]: CharacterMeta }
    years: Array<LocationSpotlightYear>
}
