// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { YearlyRankEntry } from './YearlyRankEntry'

export type LocationSpotlightYear = {
    year: number
    locations: Array<YearlyRankEntry>
}
