// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemId } from './ItemId'

export type LocationBreakoutYear = {
    id: ItemId
    name: string
    breakoutYears: Array<number>
    breakoutCount: number
    avgPerYear: number
    ratio: number
}
