// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocationTurnoverYear = {
    year: number
    newLocations: number
    continuingLocations: number
    returningLocations: number
    droppedLocations: number
}
