// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocationCoOccurrenceEntry } from './LocationCoOccurrenceEntry'
import type { LocationCoOccurrencePair } from './LocationCoOccurrencePair'

export type LocationCoOccurrenceResponse = {
    locations: { [key in number]: LocationCoOccurrenceEntry }
    pairs: Array<LocationCoOccurrencePair>
}
