// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemId } from './ItemId'

export type LonerEntry = {
    id: ItemId
    name: string
    appearances: number
    avgCoCast: number
}
