// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicId } from './ComicId'

export type MilestoneComic = {
    comicId: ComicId
    title: string
    pubDate: string | null
    isGuestComic: boolean
    isNonCanon: boolean
}
