// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemId } from './ItemId'

export type NeverMetPair = {
    character1Id: ItemId
    character1Name: string
    character1Appearances: number
    character2Id: ItemId
    character2Name: string
    character2Appearances: number
    comicsTogether: number
}
