// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicId } from './ComicId'
import type { ItemType } from './ItemType'

export type PatchItemBody = {
    name?: string
    shortName?: string
    color?: string
    type?: ItemType
    /**
     * Only meaningful for storyline items.
     */
    startComicId?: ComicId
    /**
     * Only meaningful for storyline items. Three states: field omitted
     * (don't touch), `null` (ongoing), or a value (finished at that comic).
     */
    endComicId?: ComicId | null
}
