// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemType } from './ItemType'
import type { Token } from './Token'

export type PatchItemBody = {
    token: Token
    name?: string
    shortName?: string
    color?: string
    type?: ItemType
}
