// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActiveStorylineSummary } from './ActiveStorylineSummary'
import type { ComicId } from './ComicId'
import type { ImageType } from './ImageType'
import type { ItemNavigationData } from './ItemNavigationData'
import type { True } from './True'

export type PresentComic = {
    hasData: True
    imageType: ImageType | null
    publishDate: string | null
    isAccuratePublishDate: boolean
    title: string
    tagline: string | null
    isGuestComic: boolean
    isNonCanon: boolean
    hasNoCast: boolean
    hasNoLocation: boolean
    hasNoStoryline: boolean
    hasNoTitle: boolean
    hasNoTagline: boolean
    news: string | null
    previous: ComicId | null
    next: ComicId | null
    items: Array<ItemNavigationData>
    /**
     * Every storyline active at this comic (`startComicId <= comic` and
     * `endComicId` is `null` or greater than `comic`), regardless of
     * whether it's attached to this comic — unlike `items`, which is
     * attachment-only.
     */
    activeStorylines: Array<ActiveStorylineSummary>
}
