// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MissingNavigationData } from './MissingNavigationData'
import type { True } from './True'

export type PresentEditorData = {
    present: True
    missing: MissingNavigationData
}
