// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DailyComics } from './DailyComics'
import type { MonthlyComics } from './MonthlyComics'

export type PublicationCalendar = {
    monthly: Array<MonthlyComics>
    daily: Array<DailyComics>
}
