// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicId } from './ComicId'

export type PublicationGap = {
    beforeComic: ComicId
    afterComic: ComicId
    gapDays: number
}
