// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicId } from './ComicId'
import type { ItemId } from './ItemId'

export type RemoveItemFromComicBody = { comicId: ComicId; itemId: ItemId }
