// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterMeta } from './CharacterMeta'
import type { TopRankedStint } from './TopRankedStint'

export type TopRankedOverTimeResponse = {
    stints: Array<TopRankedStint>
    characters: { [key in number]: CharacterMeta }
}
