// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemId } from './ItemId'

export type TrendingItem = {
    id: ItemId
    name: string
    totalAppearances: number
    recentAppearances: number
    careerYears: number
}
