language: node_js
node_js:
  - "4.5.0"
before_install: 
  - npm install -g grunt-cli
  - rvm install 2.4.1
  - gem install sass --version "=3.4.23"
  - gem install compass --version "=1.0.3"
install:
  - npm update -g
  - npm install
script: grunt build
