// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/DeleteItemdataImageImageId'
import type {
    DeleteItemdataImageImageIdBody,
    DeleteItemdataImageImageIdPathParams,
    DeleteItemdataImageImageIdResponse,
} from '../endpoints/DeleteItemdataImageImageId'

export async function deleteItemdataImageImageId(
    pathParams: DeleteItemdataImageImageIdPathParams,
    body: DeleteItemdataImageImageIdBody,
    options?: Omit<RequestInit, 'method'>
): Promise<DeleteItemdataImageImageIdResponse> {
    return callEndpoint<
        never,
        DeleteItemdataImageImageIdBody,
        DeleteItemdataImageImageIdPathParams,
        DeleteItemdataImageImageIdResponse,
        never
    >(spec, { body, pathParams }, options)
}
