// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetComicdataContainingItems'
import type {
    GetComicdataContainingItemsQuery,
    GetComicdataContainingItemsResponse,
} from '../endpoints/GetComicdataContainingItems'

export async function getComicdataContainingItems(
    query?: GetComicdataContainingItemsQuery,
    options?: Omit<RequestInit, 'method'>
): Promise<GetComicdataContainingItemsResponse> {
    return callEndpoint<
        GetComicdataContainingItemsQuery,
        never,
        never,
        GetComicdataContainingItemsResponse,
        never
    >(spec, { query }, options)
}
