// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetComicdataAdvance'
import type {
    GetComicdataAdvanceQuery,
    GetComicdataAdvanceResponse,
} from '../endpoints/GetComicdataAdvance'

export async function getComicdataAdvance(
    query?: GetComicdataAdvanceQuery,
    options?: Omit<RequestInit, 'method'>
): Promise<GetComicdataAdvanceResponse> {
    return callEndpoint<
        GetComicdataAdvanceQuery,
        never,
        never,
        GetComicdataAdvanceResponse,
        never
    >(spec, { query }, options)
}
