// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetComicdata'
import type {
    GetComicdataQuery,
    GetComicdataResponse,
} from '../endpoints/GetComicdata'

export async function getComicdata(
    query?: GetComicdataQuery,
    options?: Omit<RequestInit, 'method'>
): Promise<GetComicdataResponse> {
    return callEndpoint<
        GetComicdataQuery,
        never,
        never,
        GetComicdataResponse,
        never
    >(spec, { query }, options)
}
