// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetComicdataComicId'
import type {
    GetComicdataComicIdPathParams,
    GetComicdataComicIdQuery,
    GetComicdataComicIdResponse,
} from '../endpoints/GetComicdataComicId'

export async function getComicdataComicId(
    pathParams: GetComicdataComicIdPathParams,
    query?: GetComicdataComicIdQuery,
    options?: Omit<RequestInit, 'method'>
): Promise<GetComicdataComicIdResponse> {
    return callEndpoint<
        GetComicdataComicIdQuery,
        never,
        GetComicdataComicIdPathParams,
        GetComicdataComicIdResponse,
        never
    >(spec, { query, pathParams }, options)
}
