// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetComicdataExcluded'
import type {
    GetComicdataExcludedQuery,
    GetComicdataExcludedResponse,
} from '../endpoints/GetComicdataExcluded'

export async function getComicdataExcluded(
    query?: GetComicdataExcludedQuery,
    options?: Omit<RequestInit, 'method'>
): Promise<GetComicdataExcludedResponse> {
    return callEndpoint<
        GetComicdataExcludedQuery,
        never,
        never,
        GetComicdataExcludedResponse,
        never
    >(spec, { query }, options)
}
