// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetComicdataAdvance'
import type { GetComicdataAdvanceResponse } from '../endpoints/GetComicdataAdvance'

export async function getComicdataAdvance(
    options?: Omit<RequestInit, 'method'>
): Promise<GetComicdataAdvanceResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetComicdataAdvanceResponse,
        never
    >(spec, undefined, options)
}
