// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetItemdataItemIdImages'
import type {
    GetItemdataItemIdImagesPathParams,
    GetItemdataItemIdImagesResponse,
} from '../endpoints/GetItemdataItemIdImages'

export async function getItemdataItemIdImages(
    pathParams: GetItemdataItemIdImagesPathParams,
    options?: Omit<RequestInit, 'method'>
): Promise<GetItemdataItemIdImagesResponse> {
    return callEndpoint<
        never,
        never,
        GetItemdataItemIdImagesPathParams,
        GetItemdataItemIdImagesResponse,
        never
    >(spec, { pathParams }, options)
}
