// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetItemdata'
import type { GetItemdataResponse } from '../endpoints/GetItemdata'

export async function getItemdata(
    options?: Omit<RequestInit, 'method'>
): Promise<GetItemdataResponse> {
    return callEndpoint<never, never, never, GetItemdataResponse, never>(
        spec,
        undefined,
        options
    )
}
