// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetItemdataItemIdComics'
import type {
    GetItemdataItemIdComicsPathParams,
    GetItemdataItemIdComicsResponse,
} from '../endpoints/GetItemdataItemIdComics'

export async function getItemdataItemIdComics(
    pathParams: GetItemdataItemIdComicsPathParams,
    options?: Omit<RequestInit, 'method'>
): Promise<GetItemdataItemIdComicsResponse> {
    return callEndpoint<
        never,
        never,
        GetItemdataItemIdComicsPathParams,
        GetItemdataItemIdComicsResponse,
        never
    >(spec, { pathParams }, options)
}
