// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetItemdataItemIdFriends'
import type {
    GetItemdataItemIdFriendsPathParams,
    GetItemdataItemIdFriendsResponse,
} from '../endpoints/GetItemdataItemIdFriends'

export async function getItemdataItemIdFriends(
    pathParams: GetItemdataItemIdFriendsPathParams,
    options?: Omit<RequestInit, 'method'>
): Promise<GetItemdataItemIdFriendsResponse> {
    return callEndpoint<
        never,
        never,
        GetItemdataItemIdFriendsPathParams,
        GetItemdataItemIdFriendsResponse,
        never
    >(spec, { pathParams }, options)
}
