// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetItemdataItemId'
import type {
    GetItemdataItemIdPathParams,
    GetItemdataItemIdResponse,
} from '../endpoints/GetItemdataItemId'

export async function getItemdataItemId(
    pathParams: GetItemdataItemIdPathParams,
    options?: Omit<RequestInit, 'method'>
): Promise<GetItemdataItemIdResponse> {
    return callEndpoint<
        never,
        never,
        GetItemdataItemIdPathParams,
        GetItemdataItemIdResponse,
        never
    >(spec, { pathParams }, options)
}
