// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetItemdataItemIdComicsRandom'
import type {
    GetItemdataItemIdComicsRandomPathParams,
    GetItemdataItemIdComicsRandomQuery,
    GetItemdataItemIdComicsRandomResponse,
} from '../endpoints/GetItemdataItemIdComicsRandom'

export async function getItemdataItemIdComicsRandom(
    pathParams: GetItemdataItemIdComicsRandomPathParams,
    query?: GetItemdataItemIdComicsRandomQuery,
    options?: Omit<RequestInit, 'method'>
): Promise<GetItemdataItemIdComicsRandomResponse> {
    return callEndpoint<
        GetItemdataItemIdComicsRandomQuery,
        never,
        GetItemdataItemIdComicsRandomPathParams,
        GetItemdataItemIdComicsRandomResponse,
        never
    >(spec, { query, pathParams }, options)
}
