// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetItemdataItemIdLocations'
import type {
    GetItemdataItemIdLocationsPathParams,
    GetItemdataItemIdLocationsResponse,
} from '../endpoints/GetItemdataItemIdLocations'

export async function getItemdataItemIdLocations(
    pathParams: GetItemdataItemIdLocationsPathParams,
    options?: Omit<RequestInit, 'method'>
): Promise<GetItemdataItemIdLocationsResponse> {
    return callEndpoint<
        never,
        never,
        GetItemdataItemIdLocationsPathParams,
        GetItemdataItemIdLocationsResponse,
        never
    >(spec, { pathParams }, options)
}
