// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetLog'
import type { GetLogQuery, GetLogResponse } from '../endpoints/GetLog'

export async function getLog(
    query?: GetLogQuery,
    options?: Omit<RequestInit, 'method'>
): Promise<GetLogResponse> {
    return callEndpoint<GetLogQuery, never, never, GetLogResponse, never>(
        spec,
        { query },
        options
    )
}
