// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetLogComic'
import type {
    GetLogComicQuery,
    GetLogComicResponse,
} from '../endpoints/GetLogComic'

export async function getLogComic(
    query?: GetLogComicQuery,
    options?: Omit<RequestInit, 'method'>
): Promise<GetLogComicResponse> {
    return callEndpoint<
        GetLogComicQuery,
        never,
        never,
        GetLogComicResponse,
        never
    >(spec, { query }, options)
}
