// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetLogItem'
import type {
    GetLogItemQuery,
    GetLogItemResponse,
} from '../endpoints/GetLogItem'

export async function getLogItem(
    query?: GetLogItemQuery,
    options?: Omit<RequestInit, 'method'>
): Promise<GetLogItemResponse> {
    return callEndpoint<
        GetLogItemQuery,
        never,
        never,
        GetLogItemResponse,
        never
    >(spec, { query }, options)
}
