// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsCharacterHomeTurf'
import type { GetStatsCharacterHomeTurfResponse } from '../endpoints/GetStatsCharacterHomeTurf'

export async function getStatsCharacterHomeTurf(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsCharacterHomeTurfResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsCharacterHomeTurfResponse,
        never
    >(spec, undefined, options)
}
