// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsComebackLocations'
import type { GetStatsComebackLocationsResponse } from '../endpoints/GetStatsComebackLocations'

export async function getStatsComebackLocations(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsComebackLocationsResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsComebackLocationsResponse,
        never
    >(spec, undefined, options)
}
