// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsMonthlyHeatmap'
import type { GetStatsMonthlyHeatmapResponse } from '../endpoints/GetStatsMonthlyHeatmap'

export async function getStatsMonthlyHeatmap(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsMonthlyHeatmapResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsMonthlyHeatmapResponse,
        never
    >(spec, undefined, options)
}
