// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsCrowdedComics'
import type { GetStatsCrowdedComicsResponse } from '../endpoints/GetStatsCrowdedComics'

export async function getStatsCrowdedComics(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsCrowdedComicsResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsCrowdedComicsResponse,
        never
    >(spec, undefined, options)
}
