// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsComebackCharacters'
import type { GetStatsComebackCharactersResponse } from '../endpoints/GetStatsComebackCharacters'

export async function getStatsComebackCharacters(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsComebackCharactersResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsComebackCharactersResponse,
        never
    >(spec, undefined, options)
}
