// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsEnsembleRatio'
import type { GetStatsEnsembleRatioResponse } from '../endpoints/GetStatsEnsembleRatio'

export async function getStatsEnsembleRatio(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsEnsembleRatioResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsEnsembleRatioResponse,
        never
    >(spec, undefined, options)
}
