// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsPublicationStreaks'
import type { GetStatsPublicationStreaksResponse } from '../endpoints/GetStatsPublicationStreaks'

export async function getStatsPublicationStreaks(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsPublicationStreaksResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsPublicationStreaksResponse,
        never
    >(spec, undefined, options)
}
