// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsCharacterRegularity'
import type { GetStatsCharacterRegularityResponse } from '../endpoints/GetStatsCharacterRegularity'

export async function getStatsCharacterRegularity(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsCharacterRegularityResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsCharacterRegularityResponse,
        never
    >(spec, undefined, options)
}
