// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsMilestones'
import type { GetStatsMilestonesResponse } from '../endpoints/GetStatsMilestones'

export async function getStatsMilestones(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsMilestonesResponse> {
    return callEndpoint<never, never, never, GetStatsMilestonesResponse, never>(
        spec,
        undefined,
        options
    )
}
