// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsLocationCoOccurrences'
import type { GetStatsLocationCoOccurrencesResponse } from '../endpoints/GetStatsLocationCoOccurrences'

export async function getStatsLocationCoOccurrences(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsLocationCoOccurrencesResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsLocationCoOccurrencesResponse,
        never
    >(spec, undefined, options)
}
