// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsLocationBreakoutYears'
import type { GetStatsLocationBreakoutYearsResponse } from '../endpoints/GetStatsLocationBreakoutYears'

export async function getStatsLocationBreakoutYears(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsLocationBreakoutYearsResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsLocationBreakoutYearsResponse,
        never
    >(spec, undefined, options)
}
