// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsNeverMet'
import type { GetStatsNeverMetResponse } from '../endpoints/GetStatsNeverMet'

export async function getStatsNeverMet(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsNeverMetResponse> {
    return callEndpoint<never, never, never, GetStatsNeverMetResponse, never>(
        spec,
        undefined,
        options
    )
}
