// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsBreakoutYears'
import type { GetStatsBreakoutYearsResponse } from '../endpoints/GetStatsBreakoutYears'

export async function getStatsBreakoutYears(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsBreakoutYearsResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsBreakoutYearsResponse,
        never
    >(spec, undefined, options)
}
