// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsPublicationCalendar'
import type { GetStatsPublicationCalendarResponse } from '../endpoints/GetStatsPublicationCalendar'

export async function getStatsPublicationCalendar(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsPublicationCalendarResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsPublicationCalendarResponse,
        never
    >(spec, undefined, options)
}
