// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsYearlyOverview'
import type { GetStatsYearlyOverviewResponse } from '../endpoints/GetStatsYearlyOverview'

export async function getStatsYearlyOverview(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsYearlyOverviewResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsYearlyOverviewResponse,
        never
    >(spec, undefined, options)
}
