// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsTopRankedOverTime'
import type { GetStatsTopRankedOverTimeResponse } from '../endpoints/GetStatsTopRankedOverTime'

export async function getStatsTopRankedOverTime(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsTopRankedOverTimeResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsTopRankedOverTimeResponse,
        never
    >(spec, undefined, options)
}
