// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsScheduleEvolution'
import type { GetStatsScheduleEvolutionResponse } from '../endpoints/GetStatsScheduleEvolution'

export async function getStatsScheduleEvolution(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsScheduleEvolutionResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsScheduleEvolutionResponse,
        never
    >(spec, undefined, options)
}
