// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsLocationYearlySpotlight'
import type { GetStatsLocationYearlySpotlightResponse } from '../endpoints/GetStatsLocationYearlySpotlight'

export async function getStatsLocationYearlySpotlight(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsLocationYearlySpotlightResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsLocationYearlySpotlightResponse,
        never
    >(spec, undefined, options)
}
