// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsLocationRegularity'
import type { GetStatsLocationRegularityResponse } from '../endpoints/GetStatsLocationRegularity'

export async function getStatsLocationRegularity(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsLocationRegularityResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsLocationRegularityResponse,
        never
    >(spec, undefined, options)
}
