// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsPublicationGaps'
import type { GetStatsPublicationGapsResponse } from '../endpoints/GetStatsPublicationGaps'

export async function getStatsPublicationGaps(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsPublicationGapsResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsPublicationGapsResponse,
        never
    >(spec, undefined, options)
}
