// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsDebutClusters'
import type { GetStatsDebutClustersResponse } from '../endpoints/GetStatsDebutClusters'

export async function getStatsDebutClusters(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsDebutClustersResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsDebutClustersResponse,
        never
    >(spec, undefined, options)
}
