// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsLocationAffinity'
import type { GetStatsLocationAffinityResponse } from '../endpoints/GetStatsLocationAffinity'

export async function getStatsLocationAffinity(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsLocationAffinityResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsLocationAffinityResponse,
        never
    >(spec, undefined, options)
}
