// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsLocationSeasons'
import type { GetStatsLocationSeasonsResponse } from '../endpoints/GetStatsLocationSeasons'

export async function getStatsLocationSeasons(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsLocationSeasonsResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsLocationSeasonsResponse,
        never
    >(spec, undefined, options)
}
