// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsTrendingCharacters'
import type { GetStatsTrendingCharactersResponse } from '../endpoints/GetStatsTrendingCharacters'

export async function getStatsTrendingCharacters(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsTrendingCharactersResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsTrendingCharactersResponse,
        never
    >(spec, undefined, options)
}
