// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsSocialHub'
import type { GetStatsSocialHubResponse } from '../endpoints/GetStatsSocialHub'

export async function getStatsSocialHub(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsSocialHubResponse> {
    return callEndpoint<never, never, never, GetStatsSocialHubResponse, never>(
        spec,
        undefined,
        options
    )
}
