// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsCoAppearances'
import type { GetStatsCoAppearancesResponse } from '../endpoints/GetStatsCoAppearances'

export async function getStatsCoAppearances(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsCoAppearancesResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsCoAppearancesResponse,
        never
    >(spec, undefined, options)
}
