// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsCastTurnover'
import type { GetStatsCastTurnoverResponse } from '../endpoints/GetStatsCastTurnover'

export async function getStatsCastTurnover(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsCastTurnoverResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsCastTurnoverResponse,
        never
    >(spec, undefined, options)
}
