// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsCharacterSeasons'
import type { GetStatsCharacterSeasonsResponse } from '../endpoints/GetStatsCharacterSeasons'

export async function getStatsCharacterSeasons(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsCharacterSeasonsResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsCharacterSeasonsResponse,
        never
    >(spec, undefined, options)
}
