// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsPublishTimeEvolution'
import type { GetStatsPublishTimeEvolutionResponse } from '../endpoints/GetStatsPublishTimeEvolution'

export async function getStatsPublishTimeEvolution(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsPublishTimeEvolutionResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsPublishTimeEvolutionResponse,
        never
    >(spec, undefined, options)
}
