// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsLocationTurnover'
import type { GetStatsLocationTurnoverResponse } from '../endpoints/GetStatsLocationTurnover'

export async function getStatsLocationTurnover(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsLocationTurnoverResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsLocationTurnoverResponse,
        never
    >(spec, undefined, options)
}
