// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsCast'
import type { GetStatsCastResponse } from '../endpoints/GetStatsCast'

export async function getStatsCast(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsCastResponse> {
    return callEndpoint<never, never, never, GetStatsCastResponse, never>(
        spec,
        undefined,
        options
    )
}
