// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsDebutsPerYear'
import type { GetStatsDebutsPerYearResponse } from '../endpoints/GetStatsDebutsPerYear'

export async function getStatsDebutsPerYear(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsDebutsPerYearResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsDebutsPerYearResponse,
        never
    >(spec, undefined, options)
}
