// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsTrendingLocations'
import type { GetStatsTrendingLocationsResponse } from '../endpoints/GetStatsTrendingLocations'

export async function getStatsTrendingLocations(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsTrendingLocationsResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsTrendingLocationsResponse,
        never
    >(spec, undefined, options)
}
