// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsLocations'
import type { GetStatsLocationsResponse } from '../endpoints/GetStatsLocations'

export async function getStatsLocations(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsLocationsResponse> {
    return callEndpoint<never, never, never, GetStatsLocationsResponse, never>(
        spec,
        undefined,
        options
    )
}
