// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsLonerIndex'
import type { GetStatsLonerIndexResponse } from '../endpoints/GetStatsLonerIndex'

export async function getStatsLonerIndex(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsLonerIndexResponse> {
    return callEndpoint<never, never, never, GetStatsLonerIndexResponse, never>(
        spec,
        undefined,
        options
    )
}
