// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsPairEvolution'
import type {
    GetStatsPairEvolutionQuery,
    GetStatsPairEvolutionResponse,
} from '../endpoints/GetStatsPairEvolution'

export async function getStatsPairEvolution(
    query?: GetStatsPairEvolutionQuery,
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsPairEvolutionResponse> {
    return callEndpoint<
        GetStatsPairEvolutionQuery,
        never,
        never,
        GetStatsPairEvolutionResponse,
        never
    >(spec, { query }, options)
}
