// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsYearlySpotlight'
import type { GetStatsYearlySpotlightResponse } from '../endpoints/GetStatsYearlySpotlight'

export async function getStatsYearlySpotlight(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsYearlySpotlightResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsYearlySpotlightResponse,
        never
    >(spec, undefined, options)
}
