// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/GetStatsBestFriendScore'
import type { GetStatsBestFriendScoreResponse } from '../endpoints/GetStatsBestFriendScore'

export async function getStatsBestFriendScore(
    options?: Omit<RequestInit, 'method'>
): Promise<GetStatsBestFriendScoreResponse> {
    return callEndpoint<
        never,
        never,
        never,
        GetStatsBestFriendScoreResponse,
        never
    >(spec, undefined, options)
}
