// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/PatchItemdataItemId'
import type {
    PatchItemdataItemIdBody,
    PatchItemdataItemIdPathParams,
    PatchItemdataItemIdResponse,
} from '../endpoints/PatchItemdataItemId'

export async function patchItemdataItemId(
    pathParams: PatchItemdataItemIdPathParams,
    body: PatchItemdataItemIdBody,
    options?: Omit<RequestInit, 'method'>
): Promise<PatchItemdataItemIdResponse> {
    return callEndpoint<
        never,
        PatchItemdataItemIdBody,
        PatchItemdataItemIdPathParams,
        PatchItemdataItemIdResponse,
        never
    >(spec, { body, pathParams }, options)
}
