// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/PatchComicdataComicId'
import type {
    PatchComicdataComicIdBody,
    PatchComicdataComicIdPathParams,
    PatchComicdataComicIdResponse,
} from '../endpoints/PatchComicdataComicId'

export async function patchComicdataComicId(
    pathParams: PatchComicdataComicIdPathParams,
    body: PatchComicdataComicIdBody,
    options?: Omit<RequestInit, 'method'>
): Promise<PatchComicdataComicIdResponse> {
    return callEndpoint<
        never,
        PatchComicdataComicIdBody,
        PatchComicdataComicIdPathParams,
        PatchComicdataComicIdResponse,
        never
    >(spec, { body, pathParams }, options)
}
