// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/PostComicdataRemoveitem'
import type {
    PostComicdataRemoveitemBody,
    PostComicdataRemoveitemResponse,
} from '../endpoints/PostComicdataRemoveitem'

export async function postComicdataRemoveitem(
    body: PostComicdataRemoveitemBody,
    options?: Omit<RequestInit, 'method'>
): Promise<PostComicdataRemoveitemResponse> {
    return callEndpoint<
        never,
        PostComicdataRemoveitemBody,
        never,
        PostComicdataRemoveitemResponse,
        never
    >(spec, { body }, options)
}
