// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/PostComicdataAdvanceRunUpdater'
import type { PostComicdataAdvanceRunUpdaterResponse } from '../endpoints/PostComicdataAdvanceRunUpdater'

export async function postComicdataAdvanceRunUpdater(
    options?: Omit<RequestInit, 'method'>
): Promise<PostComicdataAdvanceRunUpdaterResponse> {
    return callEndpoint<
        never,
        never,
        never,
        PostComicdataAdvanceRunUpdaterResponse,
        never
    >(spec, undefined, options)
}
