// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/PostComicdataAdditems'
import type {
    PostComicdataAdditemsBody,
    PostComicdataAdditemsResponse,
} from '../endpoints/PostComicdataAdditems'

export async function postComicdataAdditems(
    body: PostComicdataAdditemsBody,
    options?: Omit<RequestInit, 'method'>
): Promise<PostComicdataAdditemsResponse> {
    return callEndpoint<
        never,
        PostComicdataAdditemsBody,
        never,
        PostComicdataAdditemsResponse,
        never
    >(spec, { body }, options)
}
