// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/PostItemdataItemIdImagesPrimary'
import type {
    PostItemdataItemIdImagesPrimaryBody,
    PostItemdataItemIdImagesPrimaryPathParams,
    PostItemdataItemIdImagesPrimaryResponse,
} from '../endpoints/PostItemdataItemIdImagesPrimary'

export async function postItemdataItemIdImagesPrimary(
    pathParams: PostItemdataItemIdImagesPrimaryPathParams,
    body: PostItemdataItemIdImagesPrimaryBody,
    options?: Omit<RequestInit, 'method'>
): Promise<PostItemdataItemIdImagesPrimaryResponse> {
    return callEndpoint<
        never,
        PostItemdataItemIdImagesPrimaryBody,
        PostItemdataItemIdImagesPrimaryPathParams,
        PostItemdataItemIdImagesPrimaryResponse,
        never
    >(spec, { body, pathParams }, options)
}
