// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/PostComicdataAdditem'
import type {
    PostComicdataAdditemBody,
    PostComicdataAdditemResponse,
} from '../endpoints/PostComicdataAdditem'

export async function postComicdataAdditem(
    body: PostComicdataAdditemBody,
    options?: Omit<RequestInit, 'method'>
): Promise<PostComicdataAdditemResponse> {
    return callEndpoint<
        never,
        PostComicdataAdditemBody,
        never,
        PostComicdataAdditemResponse,
        never
    >(spec, { body }, options)
}
