// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/PostComicdataAdvanceRunUpdater'
import type {
    PostComicdataAdvanceRunUpdaterBody,
    PostComicdataAdvanceRunUpdaterResponse,
} from '../endpoints/PostComicdataAdvanceRunUpdater'

export async function postComicdataAdvanceRunUpdater(
    body: PostComicdataAdvanceRunUpdaterBody,
    options?: Omit<RequestInit, 'method'>
): Promise<PostComicdataAdvanceRunUpdaterResponse> {
    return callEndpoint<
        never,
        PostComicdataAdvanceRunUpdaterBody,
        never,
        PostComicdataAdvanceRunUpdaterResponse,
        never
    >(spec, { body }, options)
}
