// This file was generated by the api_endpoint macro. Do not edit this file manually.
import { callEndpoint } from '../../services/callEndpoint'
import spec from '../endpoints/PostComicdataAdvance'
import type {
    PostComicdataAdvanceBody,
    PostComicdataAdvanceResponse,
} from '../endpoints/PostComicdataAdvance'

export async function postComicdataAdvance(
    body: PostComicdataAdvanceBody,
    options?: Omit<RequestInit, 'method'>
): Promise<PostComicdataAdvanceResponse> {
    return callEndpoint<
        never,
        PostComicdataAdvanceBody,
        never,
        PostComicdataAdvanceResponse,
        never
    >(spec, { body }, options)
}
