// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { EndpointSpec } from './EndpointSpec'

export const DeleteItemdataImageImageIdMethod = 'DELETE' as const
export const DeleteItemdataImageImageIdPath =
    'itemdata/image/{imageId}' as const
export type DeleteItemdataImageImageIdQuery = never
export type DeleteItemdataImageImageIdBody = never
export type DeleteItemdataImageImageIdPathParams = number
export type DeleteItemdataImageImageIdResponse = string

export default {
    method: DeleteItemdataImageImageIdMethod,
    path: DeleteItemdataImageImageIdPath,
} satisfies EndpointSpec<
    DeleteItemdataImageImageIdQuery,
    DeleteItemdataImageImageIdBody,
    DeleteItemdataImageImageIdPathParams,
    DeleteItemdataImageImageIdResponse
>
