// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { ComicList } from '../models/ComicList'
import type { ExcludedQuery } from '../models/ExcludedQuery'
import type { EndpointSpec } from './EndpointSpec'

export const GetComicdataExcludedMethod = 'GET' as const
export const GetComicdataExcludedPath = 'comicdata/excluded' as const
export type GetComicdataExcludedQuery = ExcludedQuery
export type GetComicdataExcludedBody = never
export type GetComicdataExcludedPathParams = never
export type GetComicdataExcludedResponse = Array<ComicList>

export default {
    method: GetComicdataExcludedMethod,
    path: GetComicdataExcludedPath,
} satisfies EndpointSpec<
    GetComicdataExcludedQuery,
    GetComicdataExcludedBody,
    GetComicdataExcludedPathParams,
    GetComicdataExcludedResponse
>
