// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { AllQuery } from '../models/AllQuery'
import type { ComicList } from '../models/ComicList'
import type { EndpointSpec } from './EndpointSpec'

export const GetComicdataMethod = 'GET' as const
export const GetComicdataPath = 'comicdata/' as const
export type GetComicdataQuery = AllQuery
export type GetComicdataBody = never
export type GetComicdataPathParams = never
export type GetComicdataResponse = Array<ComicList>

export default {
    method: GetComicdataMethod,
    path: GetComicdataPath,
} satisfies EndpointSpec<
    GetComicdataQuery,
    GetComicdataBody,
    GetComicdataPathParams,
    GetComicdataResponse
>
