// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { FilteredQuery } from '../models/FilteredQuery'
import type { EndpointSpec } from './EndpointSpec'

export const GetComicdataContainingItemsMethod = 'GET' as const
export const GetComicdataContainingItemsPath =
    'comicdata/containing-items' as const
export type GetComicdataContainingItemsQuery = FilteredQuery
export type GetComicdataContainingItemsBody = never
export type GetComicdataContainingItemsPathParams = never
export type GetComicdataContainingItemsResponse = Array<number>

export default {
    method: GetComicdataContainingItemsMethod,
    path: GetComicdataContainingItemsPath,
} satisfies EndpointSpec<
    GetComicdataContainingItemsQuery,
    GetComicdataContainingItemsBody,
    GetComicdataContainingItemsPathParams,
    GetComicdataContainingItemsResponse
>
