// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { AdvanceComicListItem } from '../models/AdvanceComicListItem'
import type { ListAdvanceComicsQuery } from '../models/ListAdvanceComicsQuery'
import type { EndpointSpec } from './EndpointSpec'

export const GetComicdataAdvanceMethod = 'GET' as const
export const GetComicdataAdvancePath = 'comicdata/advance' as const
export type GetComicdataAdvanceQuery = ListAdvanceComicsQuery
export type GetComicdataAdvanceBody = never
export type GetComicdataAdvancePathParams = never
export type GetComicdataAdvanceResponse = Array<AdvanceComicListItem>

export default {
    method: GetComicdataAdvanceMethod,
    path: GetComicdataAdvancePath,
} satisfies EndpointSpec<
    GetComicdataAdvanceQuery,
    GetComicdataAdvanceBody,
    GetComicdataAdvancePathParams,
    GetComicdataAdvanceResponse
>
