// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { ByIdQuery } from '../models/ByIdQuery'
import type { Comic } from '../models/Comic'
import type { ComicId } from '../models/ComicId'
import type { EndpointSpec } from './EndpointSpec'

export const GetComicdataComicIdMethod = 'GET' as const
export const GetComicdataComicIdPath = 'comicdata/{comicId}' as const
export type GetComicdataComicIdQuery = ByIdQuery
export type GetComicdataComicIdBody = never
export type GetComicdataComicIdPathParams = ComicId
export type GetComicdataComicIdResponse = Comic

export default {
    method: GetComicdataComicIdMethod,
    path: GetComicdataComicIdPath,
} satisfies EndpointSpec<
    GetComicdataComicIdQuery,
    GetComicdataComicIdBody,
    GetComicdataComicIdPathParams,
    GetComicdataComicIdResponse
>
