// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { ItemImageList } from '../models/ItemImageList'
import type { EndpointSpec } from './EndpointSpec'

export const GetItemdataItemIdImagesMethod = 'GET' as const
export const GetItemdataItemIdImagesPath = 'itemdata/{itemId}/images' as const
export type GetItemdataItemIdImagesQuery = never
export type GetItemdataItemIdImagesBody = never
export type GetItemdataItemIdImagesPathParams = number
export type GetItemdataItemIdImagesResponse = Array<ItemImageList>

export default {
    method: GetItemdataItemIdImagesMethod,
    path: GetItemdataItemIdImagesPath,
} satisfies EndpointSpec<
    GetItemdataItemIdImagesQuery,
    GetItemdataItemIdImagesBody,
    GetItemdataItemIdImagesPathParams,
    GetItemdataItemIdImagesResponse
>
