// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { ComicList } from '../models/ComicList'
import type { EndpointSpec } from './EndpointSpec'

export const GetItemdataItemIdComicsMethod = 'GET' as const
export const GetItemdataItemIdComicsPath = 'itemdata/{itemId}/comics' as const
export type GetItemdataItemIdComicsQuery = never
export type GetItemdataItemIdComicsBody = never
export type GetItemdataItemIdComicsPathParams = number
export type GetItemdataItemIdComicsResponse = Array<ComicList>

export default {
    method: GetItemdataItemIdComicsMethod,
    path: GetItemdataItemIdComicsPath,
} satisfies EndpointSpec<
    GetItemdataItemIdComicsQuery,
    GetItemdataItemIdComicsBody,
    GetItemdataItemIdComicsPathParams,
    GetItemdataItemIdComicsResponse
>
