// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { RelatedItem } from '../models/RelatedItem'
import type { EndpointSpec } from './EndpointSpec'

export const GetItemdataItemIdFriendsMethod = 'GET' as const
export const GetItemdataItemIdFriendsPath = 'itemdata/{itemId}/friends' as const
export type GetItemdataItemIdFriendsQuery = never
export type GetItemdataItemIdFriendsBody = never
export type GetItemdataItemIdFriendsPathParams = number
export type GetItemdataItemIdFriendsResponse = Array<RelatedItem>

export default {
    method: GetItemdataItemIdFriendsMethod,
    path: GetItemdataItemIdFriendsPath,
} satisfies EndpointSpec<
    GetItemdataItemIdFriendsQuery,
    GetItemdataItemIdFriendsBody,
    GetItemdataItemIdFriendsPathParams,
    GetItemdataItemIdFriendsResponse
>
