// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { Item } from '../models/Item'
import type { ItemId } from '../models/ItemId'
import type { EndpointSpec } from './EndpointSpec'

export const GetItemdataItemIdMethod = 'GET' as const
export const GetItemdataItemIdPath = 'itemdata/{itemId}' as const
export type GetItemdataItemIdQuery = never
export type GetItemdataItemIdBody = never
export type GetItemdataItemIdPathParams = ItemId
export type GetItemdataItemIdResponse = Item

export default {
    method: GetItemdataItemIdMethod,
    path: GetItemdataItemIdPath,
} satisfies EndpointSpec<
    GetItemdataItemIdQuery,
    GetItemdataItemIdBody,
    GetItemdataItemIdPathParams,
    GetItemdataItemIdResponse
>
