// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { RelatedItem } from '../models/RelatedItem'
import type { EndpointSpec } from './EndpointSpec'

export const GetItemdataItemIdLocationsMethod = 'GET' as const
export const GetItemdataItemIdLocationsPath =
    'itemdata/{itemId}/locations' as const
export type GetItemdataItemIdLocationsQuery = never
export type GetItemdataItemIdLocationsBody = never
export type GetItemdataItemIdLocationsPathParams = number
export type GetItemdataItemIdLocationsResponse = Array<RelatedItem>

export default {
    method: GetItemdataItemIdLocationsMethod,
    path: GetItemdataItemIdLocationsPath,
} satisfies EndpointSpec<
    GetItemdataItemIdLocationsQuery,
    GetItemdataItemIdLocationsBody,
    GetItemdataItemIdLocationsPathParams,
    GetItemdataItemIdLocationsResponse
>
