// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { ItemList } from '../models/ItemList'
import type { EndpointSpec } from './EndpointSpec'

export const GetItemdataMethod = 'GET' as const
export const GetItemdataPath = 'itemdata/' as const
export type GetItemdataQuery = never
export type GetItemdataBody = never
export type GetItemdataPathParams = never
export type GetItemdataResponse = Array<ItemList>

export default {
    method: GetItemdataMethod,
    path: GetItemdataPath,
} satisfies EndpointSpec<
    GetItemdataQuery,
    GetItemdataBody,
    GetItemdataPathParams,
    GetItemdataResponse
>
