// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { RandomItemComicQuery } from '../models/RandomItemComicQuery'
import type { EndpointSpec } from './EndpointSpec'

export const GetItemdataItemIdComicsRandomMethod = 'GET' as const
export const GetItemdataItemIdComicsRandomPath =
    'itemdata/{itemId}/comics/random' as const
export type GetItemdataItemIdComicsRandomQuery = RandomItemComicQuery
export type GetItemdataItemIdComicsRandomBody = never
export type GetItemdataItemIdComicsRandomPathParams = number
export type GetItemdataItemIdComicsRandomResponse = number | null

export default {
    method: GetItemdataItemIdComicsRandomMethod,
    path: GetItemdataItemIdComicsRandomPath,
} satisfies EndpointSpec<
    GetItemdataItemIdComicsRandomQuery,
    GetItemdataItemIdComicsRandomBody,
    GetItemdataItemIdComicsRandomPathParams,
    GetItemdataItemIdComicsRandomResponse
>
