// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { LogByIdQuery } from '../models/LogByIdQuery'
import type { LogResponse } from '../models/LogResponse'
import type { EndpointSpec } from './EndpointSpec'

export const GetLogComicMethod = 'GET' as const
export const GetLogComicPath = 'log/comic' as const
export type GetLogComicQuery = LogByIdQuery
export type GetLogComicBody = never
export type GetLogComicPathParams = never
export type GetLogComicResponse = LogResponse

export default {
    method: GetLogComicMethod,
    path: GetLogComicPath,
} satisfies EndpointSpec<
    GetLogComicQuery,
    GetLogComicBody,
    GetLogComicPathParams,
    GetLogComicResponse
>
