// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { LogQuery } from '../models/LogQuery'
import type { LogResponse } from '../models/LogResponse'
import type { EndpointSpec } from './EndpointSpec'

export const GetLogMethod = 'GET' as const
export const GetLogPath = 'log/' as const
export type GetLogQuery = LogQuery
export type GetLogBody = never
export type GetLogPathParams = never
export type GetLogResponse = LogResponse

export default {
    method: GetLogMethod,
    path: GetLogPath,
} satisfies EndpointSpec<
    GetLogQuery,
    GetLogBody,
    GetLogPathParams,
    GetLogResponse
>
