// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { LogByIdQuery } from '../models/LogByIdQuery'
import type { LogResponse } from '../models/LogResponse'
import type { EndpointSpec } from './EndpointSpec'

export const GetLogItemMethod = 'GET' as const
export const GetLogItemPath = 'log/item' as const
export type GetLogItemQuery = LogByIdQuery
export type GetLogItemBody = never
export type GetLogItemPathParams = never
export type GetLogItemResponse = LogResponse

export default {
    method: GetLogItemMethod,
    path: GetLogItemPath,
} satisfies EndpointSpec<
    GetLogItemQuery,
    GetLogItemBody,
    GetLogItemPathParams,
    GetLogItemResponse
>
