// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { MilestoneComic } from '../models/MilestoneComic'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsMilestonesMethod = 'GET' as const
export const GetStatsMilestonesPath = 'stats/milestones' as const
export type GetStatsMilestonesQuery = never
export type GetStatsMilestonesBody = never
export type GetStatsMilestonesPathParams = never
export type GetStatsMilestonesResponse = Array<MilestoneComic>

export default {
    method: GetStatsMilestonesMethod,
    path: GetStatsMilestonesPath,
} satisfies EndpointSpec<
    GetStatsMilestonesQuery,
    GetStatsMilestonesBody,
    GetStatsMilestonesPathParams,
    GetStatsMilestonesResponse
>
