// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { ComebackLocation } from '../models/ComebackLocation'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsComebackLocationsMethod = 'GET' as const
export const GetStatsComebackLocationsPath = 'stats/comeback-locations' as const
export type GetStatsComebackLocationsQuery = never
export type GetStatsComebackLocationsBody = never
export type GetStatsComebackLocationsPathParams = never
export type GetStatsComebackLocationsResponse = Array<ComebackLocation>

export default {
    method: GetStatsComebackLocationsMethod,
    path: GetStatsComebackLocationsPath,
} satisfies EndpointSpec<
    GetStatsComebackLocationsQuery,
    GetStatsComebackLocationsBody,
    GetStatsComebackLocationsPathParams,
    GetStatsComebackLocationsResponse
>
