// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { ComebackCharacter } from '../models/ComebackCharacter'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsComebackCharactersMethod = 'GET' as const
export const GetStatsComebackCharactersPath =
    'stats/comeback-characters' as const
export type GetStatsComebackCharactersQuery = never
export type GetStatsComebackCharactersBody = never
export type GetStatsComebackCharactersPathParams = never
export type GetStatsComebackCharactersResponse = Array<ComebackCharacter>

export default {
    method: GetStatsComebackCharactersMethod,
    path: GetStatsComebackCharactersPath,
} satisfies EndpointSpec<
    GetStatsComebackCharactersQuery,
    GetStatsComebackCharactersBody,
    GetStatsComebackCharactersPathParams,
    GetStatsComebackCharactersResponse
>
