// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { LocationCoOccurrenceResponse } from '../models/LocationCoOccurrenceResponse'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsLocationCoOccurrencesMethod = 'GET' as const
export const GetStatsLocationCoOccurrencesPath =
    'stats/location-co-occurrences' as const
export type GetStatsLocationCoOccurrencesQuery = never
export type GetStatsLocationCoOccurrencesBody = never
export type GetStatsLocationCoOccurrencesPathParams = never
export type GetStatsLocationCoOccurrencesResponse = LocationCoOccurrenceResponse

export default {
    method: GetStatsLocationCoOccurrencesMethod,
    path: GetStatsLocationCoOccurrencesPath,
} satisfies EndpointSpec<
    GetStatsLocationCoOccurrencesQuery,
    GetStatsLocationCoOccurrencesBody,
    GetStatsLocationCoOccurrencesPathParams,
    GetStatsLocationCoOccurrencesResponse
>
