// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { CharacterHomeTurfEntry } from '../models/CharacterHomeTurfEntry'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsCharacterHomeTurfMethod = 'GET' as const
export const GetStatsCharacterHomeTurfPath =
    'stats/character-home-turf' as const
export type GetStatsCharacterHomeTurfQuery = never
export type GetStatsCharacterHomeTurfBody = never
export type GetStatsCharacterHomeTurfPathParams = never
export type GetStatsCharacterHomeTurfResponse = Array<CharacterHomeTurfEntry>

export default {
    method: GetStatsCharacterHomeTurfMethod,
    path: GetStatsCharacterHomeTurfPath,
} satisfies EndpointSpec<
    GetStatsCharacterHomeTurfQuery,
    GetStatsCharacterHomeTurfBody,
    GetStatsCharacterHomeTurfPathParams,
    GetStatsCharacterHomeTurfResponse
>
