// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { BreakoutYear } from '../models/BreakoutYear'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsBreakoutYearsMethod = 'GET' as const
export const GetStatsBreakoutYearsPath = 'stats/breakout-years' as const
export type GetStatsBreakoutYearsQuery = never
export type GetStatsBreakoutYearsBody = never
export type GetStatsBreakoutYearsPathParams = never
export type GetStatsBreakoutYearsResponse = Array<BreakoutYear>

export default {
    method: GetStatsBreakoutYearsMethod,
    path: GetStatsBreakoutYearsPath,
} satisfies EndpointSpec<
    GetStatsBreakoutYearsQuery,
    GetStatsBreakoutYearsBody,
    GetStatsBreakoutYearsPathParams,
    GetStatsBreakoutYearsResponse
>
