// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { PairEvolutionQuery } from '../models/PairEvolutionQuery'
import type { PairEvolutionYear } from '../models/PairEvolutionYear'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsPairEvolutionMethod = 'GET' as const
export const GetStatsPairEvolutionPath = 'stats/pair-evolution' as const
export type GetStatsPairEvolutionQuery = PairEvolutionQuery
export type GetStatsPairEvolutionBody = never
export type GetStatsPairEvolutionPathParams = never
export type GetStatsPairEvolutionResponse = Array<PairEvolutionYear>

export default {
    method: GetStatsPairEvolutionMethod,
    path: GetStatsPairEvolutionPath,
} satisfies EndpointSpec<
    GetStatsPairEvolutionQuery,
    GetStatsPairEvolutionBody,
    GetStatsPairEvolutionPathParams,
    GetStatsPairEvolutionResponse
>
