// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { YearlySpotlightResponse } from '../models/YearlySpotlightResponse'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsYearlySpotlightMethod = 'GET' as const
export const GetStatsYearlySpotlightPath = 'stats/yearly-spotlight' as const
export type GetStatsYearlySpotlightQuery = never
export type GetStatsYearlySpotlightBody = never
export type GetStatsYearlySpotlightPathParams = never
export type GetStatsYearlySpotlightResponse = YearlySpotlightResponse

export default {
    method: GetStatsYearlySpotlightMethod,
    path: GetStatsYearlySpotlightPath,
} satisfies EndpointSpec<
    GetStatsYearlySpotlightQuery,
    GetStatsYearlySpotlightBody,
    GetStatsYearlySpotlightPathParams,
    GetStatsYearlySpotlightResponse
>
