// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { SocialHubEntry } from '../models/SocialHubEntry'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsSocialHubMethod = 'GET' as const
export const GetStatsSocialHubPath = 'stats/social-hub' as const
export type GetStatsSocialHubQuery = never
export type GetStatsSocialHubBody = never
export type GetStatsSocialHubPathParams = never
export type GetStatsSocialHubResponse = Array<SocialHubEntry>

export default {
    method: GetStatsSocialHubMethod,
    path: GetStatsSocialHubPath,
} satisfies EndpointSpec<
    GetStatsSocialHubQuery,
    GetStatsSocialHubBody,
    GetStatsSocialHubPathParams,
    GetStatsSocialHubResponse
>
