// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { LocationRegularity } from '../models/LocationRegularity'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsLocationRegularityMethod = 'GET' as const
export const GetStatsLocationRegularityPath =
    'stats/location-regularity' as const
export type GetStatsLocationRegularityQuery = never
export type GetStatsLocationRegularityBody = never
export type GetStatsLocationRegularityPathParams = never
export type GetStatsLocationRegularityResponse = Array<LocationRegularity>

export default {
    method: GetStatsLocationRegularityMethod,
    path: GetStatsLocationRegularityPath,
} satisfies EndpointSpec<
    GetStatsLocationRegularityQuery,
    GetStatsLocationRegularityBody,
    GetStatsLocationRegularityPathParams,
    GetStatsLocationRegularityResponse
>
