// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { BestFriendResponse } from '../models/BestFriendResponse'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsBestFriendScoreMethod = 'GET' as const
export const GetStatsBestFriendScorePath = 'stats/best-friend-score' as const
export type GetStatsBestFriendScoreQuery = never
export type GetStatsBestFriendScoreBody = never
export type GetStatsBestFriendScorePathParams = never
export type GetStatsBestFriendScoreResponse = BestFriendResponse

export default {
    method: GetStatsBestFriendScoreMethod,
    path: GetStatsBestFriendScorePath,
} satisfies EndpointSpec<
    GetStatsBestFriendScoreQuery,
    GetStatsBestFriendScoreBody,
    GetStatsBestFriendScorePathParams,
    GetStatsBestFriendScoreResponse
>
