// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { PublicationCalendar } from '../models/PublicationCalendar'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsPublicationCalendarMethod = 'GET' as const
export const GetStatsPublicationCalendarPath =
    'stats/publication-calendar' as const
export type GetStatsPublicationCalendarQuery = never
export type GetStatsPublicationCalendarBody = never
export type GetStatsPublicationCalendarPathParams = never
export type GetStatsPublicationCalendarResponse = PublicationCalendar

export default {
    method: GetStatsPublicationCalendarMethod,
    path: GetStatsPublicationCalendarPath,
} satisfies EndpointSpec<
    GetStatsPublicationCalendarQuery,
    GetStatsPublicationCalendarBody,
    GetStatsPublicationCalendarPathParams,
    GetStatsPublicationCalendarResponse
>
