// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { NeverMetPair } from '../models/NeverMetPair'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsNeverMetMethod = 'GET' as const
export const GetStatsNeverMetPath = 'stats/never-met' as const
export type GetStatsNeverMetQuery = never
export type GetStatsNeverMetBody = never
export type GetStatsNeverMetPathParams = never
export type GetStatsNeverMetResponse = Array<NeverMetPair>

export default {
    method: GetStatsNeverMetMethod,
    path: GetStatsNeverMetPath,
} satisfies EndpointSpec<
    GetStatsNeverMetQuery,
    GetStatsNeverMetBody,
    GetStatsNeverMetPathParams,
    GetStatsNeverMetResponse
>
