// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { CharacterRegularity } from '../models/CharacterRegularity'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsCharacterRegularityMethod = 'GET' as const
export const GetStatsCharacterRegularityPath =
    'stats/character-regularity' as const
export type GetStatsCharacterRegularityQuery = never
export type GetStatsCharacterRegularityBody = never
export type GetStatsCharacterRegularityPathParams = never
export type GetStatsCharacterRegularityResponse = Array<CharacterRegularity>

export default {
    method: GetStatsCharacterRegularityMethod,
    path: GetStatsCharacterRegularityPath,
} satisfies EndpointSpec<
    GetStatsCharacterRegularityQuery,
    GetStatsCharacterRegularityBody,
    GetStatsCharacterRegularityPathParams,
    GetStatsCharacterRegularityResponse
>
