// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { MonthlyHeatmapEntry } from '../models/MonthlyHeatmapEntry'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsMonthlyHeatmapMethod = 'GET' as const
export const GetStatsMonthlyHeatmapPath = 'stats/monthly-heatmap' as const
export type GetStatsMonthlyHeatmapQuery = never
export type GetStatsMonthlyHeatmapBody = never
export type GetStatsMonthlyHeatmapPathParams = never
export type GetStatsMonthlyHeatmapResponse = Array<MonthlyHeatmapEntry>

export default {
    method: GetStatsMonthlyHeatmapMethod,
    path: GetStatsMonthlyHeatmapPath,
} satisfies EndpointSpec<
    GetStatsMonthlyHeatmapQuery,
    GetStatsMonthlyHeatmapBody,
    GetStatsMonthlyHeatmapPathParams,
    GetStatsMonthlyHeatmapResponse
>
