// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { ScheduleEvolutionYear } from '../models/ScheduleEvolutionYear'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsScheduleEvolutionMethod = 'GET' as const
export const GetStatsScheduleEvolutionPath = 'stats/schedule-evolution' as const
export type GetStatsScheduleEvolutionQuery = never
export type GetStatsScheduleEvolutionBody = never
export type GetStatsScheduleEvolutionPathParams = never
export type GetStatsScheduleEvolutionResponse = Array<ScheduleEvolutionYear>

export default {
    method: GetStatsScheduleEvolutionMethod,
    path: GetStatsScheduleEvolutionPath,
} satisfies EndpointSpec<
    GetStatsScheduleEvolutionQuery,
    GetStatsScheduleEvolutionBody,
    GetStatsScheduleEvolutionPathParams,
    GetStatsScheduleEvolutionResponse
>
