// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { YearlyOverview } from '../models/YearlyOverview'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsYearlyOverviewMethod = 'GET' as const
export const GetStatsYearlyOverviewPath = 'stats/yearly-overview' as const
export type GetStatsYearlyOverviewQuery = never
export type GetStatsYearlyOverviewBody = never
export type GetStatsYearlyOverviewPathParams = never
export type GetStatsYearlyOverviewResponse = Array<YearlyOverview>

export default {
    method: GetStatsYearlyOverviewMethod,
    path: GetStatsYearlyOverviewPath,
} satisfies EndpointSpec<
    GetStatsYearlyOverviewQuery,
    GetStatsYearlyOverviewBody,
    GetStatsYearlyOverviewPathParams,
    GetStatsYearlyOverviewResponse
>
