// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { TrendingItem } from '../models/TrendingItem'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsTrendingCharactersMethod = 'GET' as const
export const GetStatsTrendingCharactersPath =
    'stats/trending-characters' as const
export type GetStatsTrendingCharactersQuery = never
export type GetStatsTrendingCharactersBody = never
export type GetStatsTrendingCharactersPathParams = never
export type GetStatsTrendingCharactersResponse = Array<TrendingItem>

export default {
    method: GetStatsTrendingCharactersMethod,
    path: GetStatsTrendingCharactersPath,
} satisfies EndpointSpec<
    GetStatsTrendingCharactersQuery,
    GetStatsTrendingCharactersBody,
    GetStatsTrendingCharactersPathParams,
    GetStatsTrendingCharactersResponse
>
