// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { DebutsPerYear } from '../models/DebutsPerYear'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsDebutsPerYearMethod = 'GET' as const
export const GetStatsDebutsPerYearPath = 'stats/debuts-per-year' as const
export type GetStatsDebutsPerYearQuery = never
export type GetStatsDebutsPerYearBody = never
export type GetStatsDebutsPerYearPathParams = never
export type GetStatsDebutsPerYearResponse = Array<DebutsPerYear>

export default {
    method: GetStatsDebutsPerYearMethod,
    path: GetStatsDebutsPerYearPath,
} satisfies EndpointSpec<
    GetStatsDebutsPerYearQuery,
    GetStatsDebutsPerYearBody,
    GetStatsDebutsPerYearPathParams,
    GetStatsDebutsPerYearResponse
>
