// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { LocationBreakoutYear } from '../models/LocationBreakoutYear'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsLocationBreakoutYearsMethod = 'GET' as const
export const GetStatsLocationBreakoutYearsPath =
    'stats/location-breakout-years' as const
export type GetStatsLocationBreakoutYearsQuery = never
export type GetStatsLocationBreakoutYearsBody = never
export type GetStatsLocationBreakoutYearsPathParams = never
export type GetStatsLocationBreakoutYearsResponse = Array<LocationBreakoutYear>

export default {
    method: GetStatsLocationBreakoutYearsMethod,
    path: GetStatsLocationBreakoutYearsPath,
} satisfies EndpointSpec<
    GetStatsLocationBreakoutYearsQuery,
    GetStatsLocationBreakoutYearsBody,
    GetStatsLocationBreakoutYearsPathParams,
    GetStatsLocationBreakoutYearsResponse
>
