// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { CoAppearancesResponse } from '../models/CoAppearancesResponse'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsCoAppearancesMethod = 'GET' as const
export const GetStatsCoAppearancesPath = 'stats/co-appearances' as const
export type GetStatsCoAppearancesQuery = never
export type GetStatsCoAppearancesBody = never
export type GetStatsCoAppearancesPathParams = never
export type GetStatsCoAppearancesResponse = CoAppearancesResponse

export default {
    method: GetStatsCoAppearancesMethod,
    path: GetStatsCoAppearancesPath,
} satisfies EndpointSpec<
    GetStatsCoAppearancesQuery,
    GetStatsCoAppearancesBody,
    GetStatsCoAppearancesPathParams,
    GetStatsCoAppearancesResponse
>
