// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { TrendingItem } from '../models/TrendingItem'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsTrendingLocationsMethod = 'GET' as const
export const GetStatsTrendingLocationsPath = 'stats/trending-locations' as const
export type GetStatsTrendingLocationsQuery = never
export type GetStatsTrendingLocationsBody = never
export type GetStatsTrendingLocationsPathParams = never
export type GetStatsTrendingLocationsResponse = Array<TrendingItem>

export default {
    method: GetStatsTrendingLocationsMethod,
    path: GetStatsTrendingLocationsPath,
} satisfies EndpointSpec<
    GetStatsTrendingLocationsQuery,
    GetStatsTrendingLocationsBody,
    GetStatsTrendingLocationsPathParams,
    GetStatsTrendingLocationsResponse
>
