// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { PublishTimeYear } from '../models/PublishTimeYear'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsPublishTimeEvolutionMethod = 'GET' as const
export const GetStatsPublishTimeEvolutionPath =
    'stats/publish-time-evolution' as const
export type GetStatsPublishTimeEvolutionQuery = never
export type GetStatsPublishTimeEvolutionBody = never
export type GetStatsPublishTimeEvolutionPathParams = never
export type GetStatsPublishTimeEvolutionResponse = Array<PublishTimeYear>

export default {
    method: GetStatsPublishTimeEvolutionMethod,
    path: GetStatsPublishTimeEvolutionPath,
} satisfies EndpointSpec<
    GetStatsPublishTimeEvolutionQuery,
    GetStatsPublishTimeEvolutionBody,
    GetStatsPublishTimeEvolutionPathParams,
    GetStatsPublishTimeEvolutionResponse
>
