// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { ItemStats } from '../models/ItemStats'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsCastMethod = 'GET' as const
export const GetStatsCastPath = 'stats/cast' as const
export type GetStatsCastQuery = never
export type GetStatsCastBody = never
export type GetStatsCastPathParams = never
export type GetStatsCastResponse = Array<ItemStats>

export default {
    method: GetStatsCastMethod,
    path: GetStatsCastPath,
} satisfies EndpointSpec<
    GetStatsCastQuery,
    GetStatsCastBody,
    GetStatsCastPathParams,
    GetStatsCastResponse
>
