// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { LocationSocialHubEntry } from '../models/LocationSocialHubEntry'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsLocationSocialHubMethod = 'GET' as const
export const GetStatsLocationSocialHubPath =
    'stats/location-social-hub' as const
export type GetStatsLocationSocialHubQuery = never
export type GetStatsLocationSocialHubBody = never
export type GetStatsLocationSocialHubPathParams = never
export type GetStatsLocationSocialHubResponse = Array<LocationSocialHubEntry>

export default {
    method: GetStatsLocationSocialHubMethod,
    path: GetStatsLocationSocialHubPath,
} satisfies EndpointSpec<
    GetStatsLocationSocialHubQuery,
    GetStatsLocationSocialHubBody,
    GetStatsLocationSocialHubPathParams,
    GetStatsLocationSocialHubResponse
>
