// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { LocationSpotlightResponse } from '../models/LocationSpotlightResponse'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsLocationYearlySpotlightMethod = 'GET' as const
export const GetStatsLocationYearlySpotlightPath =
    'stats/location-yearly-spotlight' as const
export type GetStatsLocationYearlySpotlightQuery = never
export type GetStatsLocationYearlySpotlightBody = never
export type GetStatsLocationYearlySpotlightPathParams = never
export type GetStatsLocationYearlySpotlightResponse = LocationSpotlightResponse

export default {
    method: GetStatsLocationYearlySpotlightMethod,
    path: GetStatsLocationYearlySpotlightPath,
} satisfies EndpointSpec<
    GetStatsLocationYearlySpotlightQuery,
    GetStatsLocationYearlySpotlightBody,
    GetStatsLocationYearlySpotlightPathParams,
    GetStatsLocationYearlySpotlightResponse
>
