// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { PublicationStreak } from '../models/PublicationStreak'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsPublicationStreaksMethod = 'GET' as const
export const GetStatsPublicationStreaksPath =
    'stats/publication-streaks' as const
export type GetStatsPublicationStreaksQuery = never
export type GetStatsPublicationStreaksBody = never
export type GetStatsPublicationStreaksPathParams = never
export type GetStatsPublicationStreaksResponse = Array<PublicationStreak>

export default {
    method: GetStatsPublicationStreaksMethod,
    path: GetStatsPublicationStreaksPath,
} satisfies EndpointSpec<
    GetStatsPublicationStreaksQuery,
    GetStatsPublicationStreaksBody,
    GetStatsPublicationStreaksPathParams,
    GetStatsPublicationStreaksResponse
>
