// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { EnsembleRatio } from '../models/EnsembleRatio'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsEnsembleRatioMethod = 'GET' as const
export const GetStatsEnsembleRatioPath = 'stats/ensemble-ratio' as const
export type GetStatsEnsembleRatioQuery = never
export type GetStatsEnsembleRatioBody = never
export type GetStatsEnsembleRatioPathParams = never
export type GetStatsEnsembleRatioResponse = Array<EnsembleRatio>

export default {
    method: GetStatsEnsembleRatioMethod,
    path: GetStatsEnsembleRatioPath,
} satisfies EndpointSpec<
    GetStatsEnsembleRatioQuery,
    GetStatsEnsembleRatioBody,
    GetStatsEnsembleRatioPathParams,
    GetStatsEnsembleRatioResponse
>
