// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { DebutYear } from '../models/DebutYear'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsDebutClustersMethod = 'GET' as const
export const GetStatsDebutClustersPath = 'stats/debut-clusters' as const
export type GetStatsDebutClustersQuery = never
export type GetStatsDebutClustersBody = never
export type GetStatsDebutClustersPathParams = never
export type GetStatsDebutClustersResponse = Array<DebutYear>

export default {
    method: GetStatsDebutClustersMethod,
    path: GetStatsDebutClustersPath,
} satisfies EndpointSpec<
    GetStatsDebutClustersQuery,
    GetStatsDebutClustersBody,
    GetStatsDebutClustersPathParams,
    GetStatsDebutClustersResponse
>
