// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { PublicationGap } from '../models/PublicationGap'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsPublicationGapsMethod = 'GET' as const
export const GetStatsPublicationGapsPath = 'stats/publication-gaps' as const
export type GetStatsPublicationGapsQuery = never
export type GetStatsPublicationGapsBody = never
export type GetStatsPublicationGapsPathParams = never
export type GetStatsPublicationGapsResponse = Array<PublicationGap>

export default {
    method: GetStatsPublicationGapsMethod,
    path: GetStatsPublicationGapsPath,
} satisfies EndpointSpec<
    GetStatsPublicationGapsQuery,
    GetStatsPublicationGapsBody,
    GetStatsPublicationGapsPathParams,
    GetStatsPublicationGapsResponse
>
