// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { CharacterSeasonEntry } from '../models/CharacterSeasonEntry'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsCharacterSeasonsMethod = 'GET' as const
export const GetStatsCharacterSeasonsPath = 'stats/character-seasons' as const
export type GetStatsCharacterSeasonsQuery = never
export type GetStatsCharacterSeasonsBody = never
export type GetStatsCharacterSeasonsPathParams = never
export type GetStatsCharacterSeasonsResponse = Array<CharacterSeasonEntry>

export default {
    method: GetStatsCharacterSeasonsMethod,
    path: GetStatsCharacterSeasonsPath,
} satisfies EndpointSpec<
    GetStatsCharacterSeasonsQuery,
    GetStatsCharacterSeasonsBody,
    GetStatsCharacterSeasonsPathParams,
    GetStatsCharacterSeasonsResponse
>
