// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { CrowdedComicsResponse } from '../models/CrowdedComicsResponse'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsCrowdedComicsMethod = 'GET' as const
export const GetStatsCrowdedComicsPath = 'stats/crowded-comics' as const
export type GetStatsCrowdedComicsQuery = never
export type GetStatsCrowdedComicsBody = never
export type GetStatsCrowdedComicsPathParams = never
export type GetStatsCrowdedComicsResponse = CrowdedComicsResponse

export default {
    method: GetStatsCrowdedComicsMethod,
    path: GetStatsCrowdedComicsPath,
} satisfies EndpointSpec<
    GetStatsCrowdedComicsQuery,
    GetStatsCrowdedComicsBody,
    GetStatsCrowdedComicsPathParams,
    GetStatsCrowdedComicsResponse
>
