// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { LocationAffinity } from '../models/LocationAffinity'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsLocationAffinityMethod = 'GET' as const
export const GetStatsLocationAffinityPath = 'stats/location-affinity' as const
export type GetStatsLocationAffinityQuery = never
export type GetStatsLocationAffinityBody = never
export type GetStatsLocationAffinityPathParams = never
export type GetStatsLocationAffinityResponse = Array<LocationAffinity>

export default {
    method: GetStatsLocationAffinityMethod,
    path: GetStatsLocationAffinityPath,
} satisfies EndpointSpec<
    GetStatsLocationAffinityQuery,
    GetStatsLocationAffinityBody,
    GetStatsLocationAffinityPathParams,
    GetStatsLocationAffinityResponse
>
