// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { ItemStats } from '../models/ItemStats'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsLocationsMethod = 'GET' as const
export const GetStatsLocationsPath = 'stats/locations' as const
export type GetStatsLocationsQuery = never
export type GetStatsLocationsBody = never
export type GetStatsLocationsPathParams = never
export type GetStatsLocationsResponse = Array<ItemStats>

export default {
    method: GetStatsLocationsMethod,
    path: GetStatsLocationsPath,
} satisfies EndpointSpec<
    GetStatsLocationsQuery,
    GetStatsLocationsBody,
    GetStatsLocationsPathParams,
    GetStatsLocationsResponse
>
