// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { LonerEntry } from '../models/LonerEntry'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsLonerIndexMethod = 'GET' as const
export const GetStatsLonerIndexPath = 'stats/loner-index' as const
export type GetStatsLonerIndexQuery = never
export type GetStatsLonerIndexBody = never
export type GetStatsLonerIndexPathParams = never
export type GetStatsLonerIndexResponse = Array<LonerEntry>

export default {
    method: GetStatsLonerIndexMethod,
    path: GetStatsLonerIndexPath,
} satisfies EndpointSpec<
    GetStatsLonerIndexQuery,
    GetStatsLonerIndexBody,
    GetStatsLonerIndexPathParams,
    GetStatsLonerIndexResponse
>
