// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { CastTurnoverYear } from '../models/CastTurnoverYear'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsCastTurnoverMethod = 'GET' as const
export const GetStatsCastTurnoverPath = 'stats/cast-turnover' as const
export type GetStatsCastTurnoverQuery = never
export type GetStatsCastTurnoverBody = never
export type GetStatsCastTurnoverPathParams = never
export type GetStatsCastTurnoverResponse = Array<CastTurnoverYear>

export default {
    method: GetStatsCastTurnoverMethod,
    path: GetStatsCastTurnoverPath,
} satisfies EndpointSpec<
    GetStatsCastTurnoverQuery,
    GetStatsCastTurnoverBody,
    GetStatsCastTurnoverPathParams,
    GetStatsCastTurnoverResponse
>
