// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { TopRankedOverTimeResponse } from '../models/TopRankedOverTimeResponse'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsTopRankedOverTimeMethod = 'GET' as const
export const GetStatsTopRankedOverTimePath =
    'stats/top-ranked-over-time' as const
export type GetStatsTopRankedOverTimeQuery = never
export type GetStatsTopRankedOverTimeBody = never
export type GetStatsTopRankedOverTimePathParams = never
export type GetStatsTopRankedOverTimeResponse = TopRankedOverTimeResponse

export default {
    method: GetStatsTopRankedOverTimeMethod,
    path: GetStatsTopRankedOverTimePath,
} satisfies EndpointSpec<
    GetStatsTopRankedOverTimeQuery,
    GetStatsTopRankedOverTimeBody,
    GetStatsTopRankedOverTimePathParams,
    GetStatsTopRankedOverTimeResponse
>
