// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { LocationSeasonEntry } from '../models/LocationSeasonEntry'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsLocationSeasonsMethod = 'GET' as const
export const GetStatsLocationSeasonsPath = 'stats/location-seasons' as const
export type GetStatsLocationSeasonsQuery = never
export type GetStatsLocationSeasonsBody = never
export type GetStatsLocationSeasonsPathParams = never
export type GetStatsLocationSeasonsResponse = Array<LocationSeasonEntry>

export default {
    method: GetStatsLocationSeasonsMethod,
    path: GetStatsLocationSeasonsPath,
} satisfies EndpointSpec<
    GetStatsLocationSeasonsQuery,
    GetStatsLocationSeasonsBody,
    GetStatsLocationSeasonsPathParams,
    GetStatsLocationSeasonsResponse
>
