// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { LocationTurnoverYear } from '../models/LocationTurnoverYear'
import type { EndpointSpec } from './EndpointSpec'

export const GetStatsLocationTurnoverMethod = 'GET' as const
export const GetStatsLocationTurnoverPath = 'stats/location-turnover' as const
export type GetStatsLocationTurnoverQuery = never
export type GetStatsLocationTurnoverBody = never
export type GetStatsLocationTurnoverPathParams = never
export type GetStatsLocationTurnoverResponse = Array<LocationTurnoverYear>

export default {
    method: GetStatsLocationTurnoverMethod,
    path: GetStatsLocationTurnoverPath,
} satisfies EndpointSpec<
    GetStatsLocationTurnoverQuery,
    GetStatsLocationTurnoverBody,
    GetStatsLocationTurnoverPathParams,
    GetStatsLocationTurnoverResponse
>
