// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { ItemId } from '../models/ItemId'
import type { PatchItemBody } from '../models/PatchItemBody'
import type { EndpointSpec } from './EndpointSpec'

export const PatchItemdataItemIdMethod = 'PATCH' as const
export const PatchItemdataItemIdPath = 'itemdata/{itemId}' as const
export type PatchItemdataItemIdQuery = never
export type PatchItemdataItemIdBody = PatchItemBody
export type PatchItemdataItemIdPathParams = ItemId
export type PatchItemdataItemIdResponse = string

export default {
    method: PatchItemdataItemIdMethod,
    path: PatchItemdataItemIdPath,
} satisfies EndpointSpec<
    PatchItemdataItemIdQuery,
    PatchItemdataItemIdBody,
    PatchItemdataItemIdPathParams,
    PatchItemdataItemIdResponse
>
