// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { ComicId } from '../models/ComicId'
import type { PatchComicBody } from '../models/PatchComicBody'
import type { EndpointSpec } from './EndpointSpec'

export const PatchComicdataComicIdMethod = 'PATCH' as const
export const PatchComicdataComicIdPath = 'comicdata/{comicId}' as const
export type PatchComicdataComicIdQuery = never
export type PatchComicdataComicIdBody = PatchComicBody
export type PatchComicdataComicIdPathParams = ComicId
export type PatchComicdataComicIdResponse = string

export default {
    method: PatchComicdataComicIdMethod,
    path: PatchComicdataComicIdPath,
} satisfies EndpointSpec<
    PatchComicdataComicIdQuery,
    PatchComicdataComicIdBody,
    PatchComicdataComicIdPathParams,
    PatchComicdataComicIdResponse
>
