// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { AddItemsToComicBody } from '../models/AddItemsToComicBody'
import type { EndpointSpec } from './EndpointSpec'

export const PostComicdataAdditemsMethod = 'POST' as const
export const PostComicdataAdditemsPath = 'comicdata/additems' as const
export type PostComicdataAdditemsQuery = never
export type PostComicdataAdditemsBody = AddItemsToComicBody
export type PostComicdataAdditemsPathParams = never
export type PostComicdataAdditemsResponse = string

export default {
    method: PostComicdataAdditemsMethod,
    path: PostComicdataAdditemsPath,
} satisfies EndpointSpec<
    PostComicdataAdditemsQuery,
    PostComicdataAdditemsBody,
    PostComicdataAdditemsPathParams,
    PostComicdataAdditemsResponse
>
