// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { SetPrimaryImageBody } from '../models/SetPrimaryImageBody'
import type { EndpointSpec } from './EndpointSpec'

export const PostItemdataItemIdImagesPrimaryMethod = 'POST' as const
export const PostItemdataItemIdImagesPrimaryPath =
    'itemdata/{itemId}/images/primary' as const
export type PostItemdataItemIdImagesPrimaryQuery = never
export type PostItemdataItemIdImagesPrimaryBody = SetPrimaryImageBody
export type PostItemdataItemIdImagesPrimaryPathParams = number
export type PostItemdataItemIdImagesPrimaryResponse = string

export default {
    method: PostItemdataItemIdImagesPrimaryMethod,
    path: PostItemdataItemIdImagesPrimaryPath,
} satisfies EndpointSpec<
    PostItemdataItemIdImagesPrimaryQuery,
    PostItemdataItemIdImagesPrimaryBody,
    PostItemdataItemIdImagesPrimaryPathParams,
    PostItemdataItemIdImagesPrimaryResponse
>
