// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { RemoveItemFromComicBody } from '../models/RemoveItemFromComicBody'
import type { EndpointSpec } from './EndpointSpec'

export const PostComicdataRemoveitemMethod = 'POST' as const
export const PostComicdataRemoveitemPath = 'comicdata/removeitem' as const
export type PostComicdataRemoveitemQuery = never
export type PostComicdataRemoveitemBody = RemoveItemFromComicBody
export type PostComicdataRemoveitemPathParams = never
export type PostComicdataRemoveitemResponse = string

export default {
    method: PostComicdataRemoveitemMethod,
    path: PostComicdataRemoveitemPath,
} satisfies EndpointSpec<
    PostComicdataRemoveitemQuery,
    PostComicdataRemoveitemBody,
    PostComicdataRemoveitemPathParams,
    PostComicdataRemoveitemResponse
>
