// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { EndpointSpec } from './EndpointSpec'

export const PostComicdataAdvanceRunUpdaterMethod = 'POST' as const
export const PostComicdataAdvanceRunUpdaterPath =
    'comicdata/advance/run-updater' as const
export type PostComicdataAdvanceRunUpdaterQuery = never
export type PostComicdataAdvanceRunUpdaterBody = never
export type PostComicdataAdvanceRunUpdaterPathParams = never
export type PostComicdataAdvanceRunUpdaterResponse = string

export default {
    method: PostComicdataAdvanceRunUpdaterMethod,
    path: PostComicdataAdvanceRunUpdaterPath,
} satisfies EndpointSpec<
    PostComicdataAdvanceRunUpdaterQuery,
    PostComicdataAdvanceRunUpdaterBody,
    PostComicdataAdvanceRunUpdaterPathParams,
    PostComicdataAdvanceRunUpdaterResponse
>
