// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { AddAdvanceComicBody } from '../models/AddAdvanceComicBody'
import type { EndpointSpec } from './EndpointSpec'

export const PostComicdataAdvanceMethod = 'POST' as const
export const PostComicdataAdvancePath = 'comicdata/advance' as const
export type PostComicdataAdvanceQuery = never
export type PostComicdataAdvanceBody = AddAdvanceComicBody
export type PostComicdataAdvancePathParams = never
export type PostComicdataAdvanceResponse = string

export default {
    method: PostComicdataAdvanceMethod,
    path: PostComicdataAdvancePath,
} satisfies EndpointSpec<
    PostComicdataAdvanceQuery,
    PostComicdataAdvanceBody,
    PostComicdataAdvancePathParams,
    PostComicdataAdvanceResponse
>
