// This file was generated by the api_endpoint macro. Do not edit this file manually.
import type { AddItemToComicBody } from '../models/AddItemToComicBody'
import type { EndpointSpec } from './EndpointSpec'

export const PostComicdataAdditemMethod = 'POST' as const
export const PostComicdataAdditemPath = 'comicdata/additem' as const
export type PostComicdataAdditemQuery = never
export type PostComicdataAdditemBody = AddItemToComicBody
export type PostComicdataAdditemPathParams = never
export type PostComicdataAdditemResponse = string

export default {
    method: PostComicdataAdditemMethod,
    path: PostComicdataAdditemPath,
} satisfies EndpointSpec<
    PostComicdataAdditemQuery,
    PostComicdataAdditemBody,
    PostComicdataAdditemPathParams,
    PostComicdataAdditemResponse
>
