// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Exclusion } from './Exclusion'
import type { Inclusion } from './Inclusion'
import type { Token } from './Token'

export interface ByIdQuery {
    token?: Token
    exclude?: Exclusion
    include?: Inclusion
}
