// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MissingComic } from './MissingComic'
import type { PresentComic } from './PresentComic'

export type ComicData = MissingComic | PresentComic
