// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicData } from './ComicData'
import type { ComicId } from './ComicId'
import type { EditorData } from './EditorData'
import type { ItemNavigationData } from './ItemNavigationData'

export type Comic = {
    comic: ComicId
    editorData: EditorData
    allItems?: Array<ItemNavigationData>
} & ComicData
