// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemId } from './ItemId'
import type { ItemType } from './ItemType'

export interface ItemList {
    id: ItemId
    shortName: string
    name: string
    type: ItemType
    color: string
    count: bigint
}
