// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Token } from './Token'

export interface LogByIdQuery {
    token: Token
    id: number
    page: number
}
