// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NavigationData } from './NavigationData'

export interface MissingNavigationData {
    cast: NavigationData
    location: NavigationData
    storyline: NavigationData
    title: NavigationData
    tagline: NavigationData
}
