// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicId } from './ComicId'

export interface NavigationData {
    first: ComicId | null
    previous: ComicId | null
    next: ComicId | null
    last: ComicId | null
}
