// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemType } from './ItemType'
import type { True } from './True'

export interface NewItem {
    new: True
    newItemName: string
    newItemType: ItemType
}
