// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicId } from './ComicId'
import type { ImageType } from './ImageType'
import type { ItemNavigationData } from './ItemNavigationData'
import type { True } from './True'

export interface PresentComic {
    hasData: True
    imageType: ImageType | null
    publishDate: string | null
    isAccuratePublishDate: boolean
    title: string | null
    tagline: string | null
    isGuestComic: boolean
    isNonCanon: boolean
    hasNoCast: boolean
    hasNoLocation: boolean
    hasNoStoryline: boolean
    hasNoTitle: boolean
    hasNoTagline: boolean
    news: string | null
    previous: ComicId | null
    next: ComicId | null
    items: Array<ItemNavigationData>
}
