// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemId } from './ItemId'

export interface RelatedItem {
    id: ItemId
    count: number
}
