// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicId } from './ComicId'
import type { FlagType } from './FlagType'
import type { Token } from './Token'

export interface SetFlagBody {
    token: Token
    comicId: ComicId
    flagType: FlagType
    flagValue: boolean
}
