// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageId } from './ImageId'
import type { Token } from './Token'

export interface SetPrimaryImageBody {
    token: Token
    imageId: ImageId
}
