// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicId } from './ComicId'
import type { Token } from './Token'

export interface SetTitleBody {
    token: Token
    comicId: ComicId
    title: string
}
